version: '3.2'
services: 
  app:
    build: .
    depends_on:
      - mysql
      - imgserver
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      IMAGE_DATA_DIR: /data/www/images
      IMAGE_SERVER_HOST: http://localhost
      IMAGE_SERVER_PORT: 8080
      IMAGE_SERVER_PATH: /images/
      APP_SERVER_PORT: 8081
      APP_MAX_FILE_SIZE: 3084
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    volumes:
      - ./mysql/data:/docker-entrypoint-initdb.d
  imgserver:
    build: ./docker/imgserver
    volumes:
      - type: bind
        source: ./data
        target: /data
    ports:
      - "8080:80"