version: '3.2'
services: 
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    volumes:
      - ./mysql/data:/docker-entrypoint-initdb.d
  imgserver:
    build: ./docker/imgserver
    volumes:
      - type: bind
        source: ./data
        target: /data
    ports:
      - "8080:80"