version: '3'
services: 
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    volumes:
      - ./mysql/data:/docker-entrypoint-initdb.d